name: Lint and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest pexpect
    - name: Analysing the code with pylint
      run: |
        pylint ./src
    - name: Install Blender
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y wget xz-utils libxi6 libxxf86vm1 libxfixes3 libxrender1 libgl1
        wget https://download.blender.org/release/Blender3.2/blender-3.2.0-linux-x64.tar.xz
        tar xf blender-3.2.0-linux-x64.tar.xz
        sudo mv blender-3.2.0-linux-x64 /usr/local/blender
        sudo ln -s /usr/local/blender/blender /usr/bin/blender
        sudo ln -s "$(pwd)" /usr/local/blender/3.2/scripts/addons/blender_servo_animation
    - name: Run tests with pytest
      run: |
        pytest ./tests
